#!/bin/bash
# Download BAA PDFs from parliament.bangsamoro.gov.ph
# Step 1: For each BAA page URL, find the BAA number and PDF link
# Step 2: Download the PDF

UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
OUTDIR="/Users/saidamenmambayao/apps/transcriptions/docs/BAA-PDFs"
mkdir -p "$OUTDIR"

# All BAA page URLs from the listing
URLS=(
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-adopting-an-official-flag-of-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-adopting-an-official-bangsamoro-emblem-of-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-funds-for-the-operation-of-the-bangsamoro-government-from-january-one-to-december-thirty-one-two-thousand-and-twenty-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-operationalizing-the-establishment-of-the-bangsamoro-human-rights-commision-providing-for-its-mandate-powers-and-functions-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-bangsamoro-attorney-generals-office-defining-its-functions-and-powers-appropriating-funds-therefore-and-for-other-related-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-a-bangsamoro-socio-economic-development-planning-system-providing-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-adopting-the-official-hymn-of-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-bangsamoro-women-commission-of-the-barmm-providing-for-its-powers-functions-and-composition-and-appropriating-funds-therefor/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-regulating-the-operations-of-local-and-foreign-recruitment-agencies-within-the-bangsamoro-autonomous-region-in-muslim-mindanao-barmm/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-and-establishing-the-bangsamoro-youth-commission-defining-its-powers-functions-and-responsibilities-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-defining-the-power-of-appointment-in-the-bangsamoro-autonomous-region-in-muslim-mindanao-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-bangsamoro-sports-commission-providing-for-its-mandate-powers-and-functions-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-providing-the-bangsamoro-administrative-code-and-for-other-related-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-extending-the-availability-of-the-2020-bangsamoro-appropriations-to-december-31-2021-except-personnel-services-amending-for-the-purpose-section-47-of-the-general-provisions-of-bangsamoroauto/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-funds-for-the-operation-of-the-bangsamoro-government-from-january-one-to-december-thirty-one-two-thousand-and-twenty-one-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-adopting-an-official-seal-for-the-parliament-of-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-providing-for-the-bangsamoro-civil-service-code-of-the-bangsamoro-autonomous-region-in-muslim-mindanao-barmm/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-providing-for-the-establishment-management-and-support-of-a-complete-and-integrated-system-of-quality-education-in-the-bangsamoro/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-to-institutionalize-policies-for-bangsamoro-overseas-employment-and-establishing-a-standard-of-protection-and-promotion-of-the-welfare-of-overseas-bangsamoro-workers-and-theirfamilies-and-for/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-mandating-the-dual-use-of-hijri-and-gregorian-calendars-in-all-ministries-agencies-local-government-units-offices-and-institutions-in-the-bangsamoro-autonomous-region-in-muslim-mindanao-bar/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-authorizing-the-use-of-fifty-million-pesos-php-50000000-00-for-the-acquisition-of-additional-oxygen-tanks-to-be-charged-against-the-2021-quick-response-fund-on-health-of-the-bangsamoro-gove/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-the-sum-of-ten-billion-pesos-p10000000-from-the-2020-and-2021-special-development-fund-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-funds-for-the-operation-of-bangsamoro-government-from-january-one-to-december-thirty-one-two-thousand-and-twenty-two-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-extending-the-availability-of-the-general-appropriations-act-of-the-bangsamoro-until-december-31-2022-except-personnel-services-and-other-items-of-the-mooe-amending-for-the-purpose-section-4/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-upgrading-the-existing-datu-blah-sinsuat-district-hospital-in-maguindanao-from-its-present-level-i-with-a-10-bed-capacity-into-level-ii-with-an-authorized-100-bed-capacity-and-appropriating-fun/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-upgrading-the-existing-wao-district-hospital-in-lanao-del-sur-from-its-present-level-1-with-a-25-bed-capacity-into-level-1-with-an-authorized-50-bed-capacity-and-appropriating-funds-therefor-a/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-a-level-ii-district-hospital-with-one-hundred-100-bed-capacity-in-the-municipality-of-maimbung-province-of-sulu-and-appropriating-funds-therefor/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-upgrading-the-sulu-provincial-hospital-into-a-level-ii-hospital-increasing-its-bed-capacity-to-two-hundred-200-upgrading-its-professional-health-care-services-and-facilities-authorizing-th/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-upgrading-the-buluan-district-hospital-from-level-i-district-hospital-with-seventy-five-75-bed-capacity-to-level-ii-district-hospital-with-one-hundred-fifty-150-bed-capacity-in-the-municipa/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-upgrading-the-unayan-municipal-hospital-in-municipality-of-binidayan-lanao-del-sur-into-a-50-bed-capacity-district-hospital-and-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-bangsamoro-sustainable-development-board-defining-its-powers-and-functions-providing-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-funds-for-the-operation-of-the-bangsamoro-government-from-january-one-to-december-thirty-one-two-thousand-and-twenty-three-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-extending-the-availability-of-the-general-appropriations-act-of-the-bangsamoro-until-december-31-2023-except-personnel-services-and-general-administration-and-support-under-maintenance-and-o/"
"https://parliament.bangsamoro.gov.ph/bta-acts/anact-extending-the-availability-of-2020-and-2021-special-development-fund/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-providing-for-the-bangsamoro-electoral-code-of-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-a-revolving-fund-for-the-payment-of-salaries-compensation-and-emoluments-of-workers-and-personnel-of-nationally-funded-programs-deployed-in-the-bangsamoro-autonomous-region-in-mu/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-the-seat-of-government-of-the-bangsamoro-autonomous-region-in-muslim-mindanao-in-the-municipality-of-parang-province-of-maguindanao-del-norte-appropriating-funds-therefor-amendi/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-authorizing-the-continued-use-of-funds-for-the-release-and-disbursement-ofobligations-of-fy-2020-2021-and-2022-appropriations/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-governing-the-observance-of-regular-and-special-holidays-in-the-bangsamoro-autonomous-region-in-muslim-mindanao-barmm-repealing-for-the-purpose-muslim-mindanao-autonomy-act-no-17-otherwise/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-the-bangsamoro-science-high-school-system-providing-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-pahamuddin-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-kadayangan-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-nabalawag-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-old-kaabakan-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-northern-kabacan-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-malidegao-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-tugunan-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-ligawasan-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-providing-for-the-bangsamoro-local-governance-code/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-bangsamoro-kulliyyah-for-islamic-studies-repealing-muslim-mindanao-autonomy-act-no-164-otherwise-known-as-the-regional-madrasah-graduate-education-act-of-2003-providing-funds-t/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-further-continuing-the-validity-of-the-202020212022-and-2023-special-development-fund-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-extending-the-validity-of-the-general-appropriations-act-of-the-bangsamoro-for-fiscal-year-2023-until-december-31-2024-amending-for-the-purpose-section-50-of-bangsamoro-autonomy-act-no-32-a/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-nuling-in-the-province-of-maguindanao-del-norte-providing-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-datu-sinsuat-balabaran-in-the-province-of-maguindanao-del-norte-providing-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-municipality-of-sheik-abas-hamza-in-the-province-of-maguindanao-del-norte-providing-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-for-financial-assistance-to-bangsamoro-mujahideen-and-creating-the-office-of-the-bangsamoro-mujahideen-under-special-circumstance-defining-its-basic-organizational-structure-providing-funds-t/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-providing-for-the-creation-of-parliamentary-districts-in-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-the-bangsamoro-agriculture-and-fishiries-training-institute-appropriating-funds-therefor-and-for-other-pusposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-to-declare-the-burial-site-of-the-late-shiekh-salamat-hashim-moro-islamic-liberation-front-founding-chairperson-and-the-late-abdul-aziz-mimbantas-moro-islamic-liberation-front-vice-chairpers/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-a-bangsamoro-memorial-marker-and-eco-park-in-camp-abubakar-municipality-of-barira-maguindanao-del-norte-to-honor-the-shuhada-martyrs-of-the-bangsamoro-struggle-who-gave-and-devot/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-protecting-and-promoting-the-rights-of-internally-displaced-persons-of-the-bangsamoro-autonomous-region-in-muslim-mindanao-providing-mechanisms-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-supplemental-funds-for-the-operation-of-the-bangsamoro-government-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-to-recognize-develop-and-protect-the-indigenous-peoples-and-their-rights-in-the-bangsamoro-autonomous-region-in-muslim-mindanao-strengthening-the-ministry-of-indigenous-peoples-affa-2/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-funds-for-the-operation-of-the-bangsamoro-government-from-january-one-to-december-thirty-one-two-thousand-and-twenty-five-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-amending-section-5-of-bangsamoro-act-no-54-otherwise-known-as-the-act-creating-the-municipality-of-datu-balabaran-sinsuat-in-the-province-of-maguindanao-del-norte-providing-funds-th/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-amending-section-5-of-bangsamoro-act-no-55-otherwise-known-as-the-act-creating-the-municipality-of-sheikh-abas-hamza-in-the-province-of-maguindanao-del-norte-providing-funds-therefo/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-providing-for-seven-days-forfeitable-bereavement-leave-privileges-annually-with-pay-to-employees-in-the-public-and-private-sector-within-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-converting-the-iranon-district-hospital-in-the-municipality-of-parang-province-of-maguindanao-del-norte-into-a-provincial-hospital-to-be-known-as-the-iranon-provincial-hospital-and-appropriat/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-upgrading-the-maguindanao-provincial-hospital-to-be-known-as-the-bangsamoro-regional-hospital-and-medical-center-to-a-level-iii-hospital-and-thereby-increasing-its-bed-capaci/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-supplemental-funds-for-the-operation-of-the-bangsamoro-government-and-for-other-purposes-2/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-upgrading-the-datu-alawaddin-t-bandon-sr-memorial-hospital-in-the-municipality-of-sibutu-province-of-tawi-tawi-from-a-ten-bed-capacity-infirmary-to-a-twenty-five-bed-capacity-level-i-gen/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-reconstituting-the-parliamentary-districts-in-the-bangsamoro-autonomous-region-in-muslim-mindanao-amending-for-the-purpose-bangsamoro-autonomy-act-no-58-entitled-an-act-providing-fo/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-a-level-i-general-hospital-in-the-municipality-of-tipo-tipo-province-of-basilan-and-appropriating-funds-therefor/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-a-level-i-general-hospital-in-the-municipality-of-maluso-province-of-basilan-and-appropriating-funds-therefor/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-upgrading-the-existing-dr-serapio-b-montaner-jr-al-haj-memorial-hospital-from-twenty-five-to-one-hundred-bed-capacity-appropriating-funds-therefor-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-and-institutionalizing-the-salamat-excellence-award-for-leadership-program-for-the-bangsamoro-autonomous-region-in-muslim-mindanao-and-allocating-for-this-purpose-the-salamat-e/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-funds-for-the-operation-of-the-bangsamoro-government-from-january-one-to-december-thirty-one-two-thousand-and-twenty-four-and-for-other-purposes/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-prescribing-a-budget-system-for-the-bangsamoro-government/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-a-bangsamoro-transitional-justice-and-reconciliation-program-creating-for-this-purpose-the-bangsamoro-transitional-justice-and-reconciliation-commission-appropriating-funds-there/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-providing-for-the-apportionment-of-parliamentary-district-representative-seats-in-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-the-bangsamoro-nutrition-council-in-the-bangsamoro-autonomous-region-in-muslim-mindanao-providing-for-its-mandate-powers-and-functions-appropriating-funds-therefor-and-for-other-pu/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-instituting-a-labor-and-employment-code-for-the-bangsamoro-autonomous-region-to-afford-protection-to-labor-promote-employment-and-human-resources-development-ensure-industrial-peace-based-on/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-and-establishing-the-pura-municipal-hospital-in-the-municipality-of-datu-blah-t-sinsuat-province-of-maguindanao-del-norte-bangsamoro-autonomous-region-in-muslim-mindanao-appropriat/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-in-the-municipality-of-northern-kabuntalan-province-of-maguindanao-del-norte-a-level-i-general-hospital-to-be-known-as-the-northern-kabuntalan-general-hospital-and-appropriating/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-creating-and-establishing-a-level-1-general-hospital-to-be-known-as-aleem-abdulazis-s-mimbantas-memorial-hospital-in-the-municipality-of-masiu-province-of-lanao-del-sur-and-appropriating-fund/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-establishing-a-level-1-general-hospital-with-twenty-five-bed-capacity-in-the-municipality-of-south-ubian-province-of-tawi-tawi-to-be-known-as-the-south-ubian-general-hospital-and-appropriating/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-removing-the-none-of-the-above-option-from-the-official-ballot-in-the-bangsamoro-autonomous-region-amending-for-the-purpose-section-14-article-vii-of-bangsamoro-autonomy-act/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-amending-bangsamoro-autonomy-act-no-35-entitled-an-act-providing-for-the-bangsamoro-electoral-code-of-the-bangsamoro-autonomous-region-in-muslim-mindanao/"
"https://parliament.bangsamoro.gov.ph/bta-acts/an-act-appropriating-funds-for-the-operation-of-the-bangsamoro-government-from-january-one-to-december-thirty-one-two-thousand-and-twenty-six-and-for-other-purposes/"
)

echo "Total URLs: ${#URLS[@]}"
